//! The OpenPGP representation of the native Ed25519 root (ADR-002 §"GPG
//! integration", *Generate*: "Vox generates a native Ed25519 root and exports it
//! in OpenPGP format").
//!
//! This module produces the **v4 public-key packet** for an Ed25519 root and its
//! **v4 fingerprint** (RFC 4880 §12.2 / RFC 9580 §5.5.4.1): the fingerprint is
//! `SHA-1(0x99 ‖ len(2, BE) ‖ body)` over the key-packet body
//! `version(4) ‖ created(4, BE) ‖ algo(22 = EdDSALegacy) ‖ oid_len(9) ‖
//! OID(Ed25519) ‖ MPI(0x40 ‖ pubkey)`, where the MPI's bit length is 263 (the
//! `0x40` "native point" prefix contributes 7 significant bits + 256 key bits).
//!
//! The construction is pinned by two vectors: the "Alice" sample key from
//! draft-bre-openpgp-samples, and a key generated by GnuPG 2.5.20 whose
//! fingerprint was reproduced from `(pubkey, created)` alone before this code
//! was written. SHA-1 is used solely as this interop identifier — it is not a
//! security primitive anywhere in Vox (the Vox fingerprint is SHA-256 over the
//! composite key, ADR-002 §1).

use sha1::{Digest as _, Sha1};

use crate::hash::ED25519_PUB_LEN;
use crate::identity::binding::OPENPGP_V4_FPR_LEN;

/// OpenPGP public-key algorithm id for EdDSALegacy (RFC 9580 §9.1).
pub const ALGO_EDDSA_LEGACY: u8 = 22;
/// The Ed25519 curve OID (`1.3.6.1.4.1.11591.15.1`), DER body without the header.
pub const OID_ED25519: [u8; 9] = [0x2B, 0x06, 0x01, 0x04, 0x01, 0xDA, 0x47, 0x0F, 0x01];
/// Bit length of the Ed25519 public-key MPI (`0x40` prefix + 256 bits).
const MPI_BITS_ED25519: u16 = 263;

/// The v4 public-key packet **body** for an Ed25519 public key created at
/// `created` (seconds since the Unix epoch, as OpenPGP stores it).
#[must_use]
pub fn ed25519_public_key_packet_body(pubkey: &[u8; ED25519_PUB_LEN], created: u32) -> Vec<u8> {
    let mut body = Vec::with_capacity(1 + 4 + 1 + 1 + 9 + 2 + 1 + ED25519_PUB_LEN);
    body.push(4);
    body.extend_from_slice(&created.to_be_bytes());
    body.push(ALGO_EDDSA_LEGACY);
    body.push(OID_ED25519.len() as u8);
    body.extend_from_slice(&OID_ED25519);
    body.extend_from_slice(&MPI_BITS_ED25519.to_be_bytes());
    body.push(0x40);
    body.extend_from_slice(pubkey);
    body
}

/// The complete old-format OpenPGP public-key packet (tag 6, one-octet length)
/// — what `gpg --export` emits first for such a key.
#[must_use]
pub fn ed25519_public_key_packet(pubkey: &[u8; ED25519_PUB_LEN], created: u32) -> Vec<u8> {
    let body = ed25519_public_key_packet_body(pubkey, created);
    let mut out = Vec::with_capacity(2 + body.len());
    out.push(0x98);
    // 51 bytes for Ed25519, always < 192, so the one-octet old-format length applies.
    out.push(body.len() as u8);
    out.extend_from_slice(&body);
    out
}

/// The OpenPGP v4 fingerprint of an Ed25519 public key created at `created`.
#[must_use]
pub fn ed25519_v4_fingerprint(
    pubkey: &[u8; ED25519_PUB_LEN],
    created: u32,
) -> [u8; OPENPGP_V4_FPR_LEN] {
    let body = ed25519_public_key_packet_body(pubkey, created);
    let mut h = Sha1::new();
    h.update([0x99]);
    h.update((body.len() as u16).to_be_bytes());
    h.update(&body);
    let mut out = [0u8; OPENPGP_V4_FPR_LEN];
    out.copy_from_slice(&h.finalize());
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unhex<const N: usize>(s: &str) -> [u8; N] {
        let v = hex::decode(s).unwrap();
        v.as_slice().try_into().unwrap()
    }

    #[test]
    fn alice_sample_key_fingerprint() {
        // draft-bre-openpgp-samples "Alice": created 0x5C4704E9.
        let pubkey: [u8; 32] =
            unhex("ae35b0937140ab28856c504a4f84f35dc541a8f4c1de09b3942fd46fb3b5bb5d");
        let fpr = ed25519_v4_fingerprint(&pubkey, 0x5C47_04E9);
        assert_eq!(
            hex::encode_upper(fpr),
            "EB85BB5FA33A75E15E944E63F231550C4F47E38E"
        );
        // The packet reproduces the sample's first packet byte-for-byte.
        let pkt = ed25519_public_key_packet(&pubkey, 0x5C47_04E9);
        assert_eq!(pkt[0], 0x98);
        assert_eq!(pkt[1], 51);
        assert_eq!(&pkt[2..8], &[4, 0x5C, 0x47, 0x04, 0xE9, 22]);
    }

    #[test]
    fn gnupg_generated_key_fingerprint() {
        // A key generated by GnuPG 2.5.20 on 2026-09-19; gpg reported the
        // fingerprint below, and it was reproduced from (pubkey, created) alone.
        let pubkey: [u8; 32] =
            unhex("73c8c2630c4a046f4dc71db4a343b2c3b69bb04e3d9ed0a96078ccd45638c530");
        let fpr = ed25519_v4_fingerprint(&pubkey, 1_789_852_856);
        assert_eq!(
            hex::encode_upper(fpr),
            "068981C30C0EC89E3B2870DD9707D5CE8D1B1D4A"
        );
    }

    #[test]
    fn fingerprint_binds_creation_time_and_key() {
        let pubkey = [7u8; 32];
        let a = ed25519_v4_fingerprint(&pubkey, 1);
        let b = ed25519_v4_fingerprint(&pubkey, 2);
        let c = ed25519_v4_fingerprint(&[8u8; 32], 1);
        assert_ne!(a, b);
        assert_ne!(a, c);
    }
}
